#ifndef STATISTICSCALC_GLOBAL_H
#define STATISTICSCALC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATISTICSCALC_LIBRARY)
#  define STATISTICSCALCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STATISTICSCALCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STATISTICSCALC_GLOBAL_H
